spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost8081/
          predicates:
            - Path= /company/**
        - id: r2
          uri: http://localhost8082/
          predicates:
            - Path= //**

